const galleryData = [
    { src: "img/gallery/characters/accord.png", name: "Accord" },
    { src: "img/gallery/characters/akashi.png", name: "Akashi" },
    { src: "img/gallery/characters/alpha.png", name: "Alpha" },
    { src: "img/gallery/characters/amelia.png", name: "Amelia" },
    { src: "img/gallery/characters/anomaly-x23g.png", name: "Anomaly-X23G" },
    { src: "img/gallery/characters/aquarion.png", name: "Aquarion" },
    { src: "img/gallery/characters/ari.png", name: "Ari" },
    { src: "img/gallery/characters/aris.png", name: "Aris" },
    { src: "img/gallery/characters/armen.png", name: "Armen" },
    { src: "img/gallery/characters/asadullah.png", name: "Asadullah" },
    { src: "img/gallery/characters/astroboy.png", name: "AstroBoy" },
    { src: "img/gallery/characters/axol.png", name: "Axol" },
    { src: "img/gallery/characters/ayun.png", name: "Ayun" },
    { src: "img/gallery/characters/bandit.png", name: "Bandit Guy" },
    { src: "img/gallery/characters/basya.png", name: "Basya" },
    { src: "img/gallery/characters/bellboy.png", name: "Belldam" },
    { src: "img/gallery/characters/benji.png", name: "Benji" },
    { src: "img/gallery/characters/blair.png", name: "Blair" },
    { src: "img/gallery/characters/bor.png", name: "boR" },
    { src: "img/gallery/characters/bugger.png", name: "Bugger" },
    { src: "img/gallery/characters/charis.png", name: "Charis" },
    { src: "img/gallery/characters/chiffon.png", name: "Chiffon" },
    { src: "img/gallery/characters/chiko.png", name: "Chiko" },
    { src: "img/gallery/characters/circleguy.png", name: "Circle Guy" },
    { src: "img/gallery/characters/clementina.png", name: "Clementina" },
    { src: "img/gallery/characters/copykat.png", name: "CopyKat" },
    { src: "img/gallery/characters/corruptus.png", name: "Corruptus" },
    { src: "img/gallery/characters/creator.png", name: "Creator!Memphis" },
    { src: "img/gallery/characters/crescendo.png", name: "Crescendo" },
    { src: "img/gallery/characters/cubic.png", name: "Cubic" },
    { src: "img/gallery/characters/dagon.png", name: "Dagon" },
    { src: "img/gallery/characters/dango.png", name: "Dango" },
    { src: "img/gallery/characters/dayaram.png", name: "Dayaram" },
    { src: "img/gallery/characters/delta.png", name: "Delta" },
    { src: "img/gallery/characters/demetrius.png", name: "Demetrius" },
    { src: "img/gallery/characters/dendi.png", name: "Dendi" },
    { src: "img/gallery/characters/deutera.png", name: "Deutera" },
    { src: "img/gallery/characters/court.png", name: "Diamond!Memphis" },
    { src: "img/gallery/characters/dillon.png", name: "Dillon" },
    { src: "img/gallery/characters/doc.png", name: "Doc" },
    { src: "img/gallery/characters/dune.png", name: "Dunic" },
    { src: "img/gallery/characters/echo.png", name: "Echo" },
    { src: "img/gallery/characters/edgar.png", name: "Edgar" },
    { src: "img/gallery/characters/elle.png", name: "Elle" },
    { src: "img/gallery/characters/emptier.png", name: "Emptier" },
    { src: "img/gallery/characters/envy.png", name: "Envy" },
    { src: "img/gallery/characters/espresso.png", name: "Espresso" },
    { src: "img/gallery/characters/explorer.png", name: "Explorer" },
    { src: "img/gallery/characters/flambu.png", name: "Flambu" },
    { src: "img/gallery/characters/global.png", name: "Global" },
    { src: "img/gallery/characters/goatis.png", name: "Goatis" },
    { src: "img/gallery/characters/goldie.png", name: "Goldie" },
    { src: "img/gallery/characters/grey.png", name: "Grey" },
    { src: "img/gallery/characters/hanna.png", name: "Hanna" },
    { src: "img/gallery/characters/healer.png", name: "Healer" },
    { src: "img/gallery/characters/heliosol.png", name: "Heliosol" },
    { src: "img/gallery/characters/hikari.png", name: "Hikari" },
    { src: "img/gallery/characters/hilarion.png", name: "Hilarion" },
    { src: "img/gallery/characters/homo.png", name: "Homo!Memphis" },
    { src: "img/gallery/characters/hoodedspy.png", name: "Hooded Spy" },
    { src: "img/gallery/characters/hoppa.png", name: "Hoppa" },
    { src: "img/gallery/characters/ikram.png", name: "Ikram" },
    { src: "img/gallery/characters/inflictor.png", name: "Inflictor" },
    { src: "img/gallery/characters/iriseis.png", name: "Iriseis" },
    { src: "img/gallery/characters/isamu.png", name: "Isamu" },
    { src: "img/gallery/characters/isedroid.png", name: "Isedroid" },
    { src: "img/gallery/characters/ixaptron.png", name: "Ixaptron" },
    { src: "img/gallery/characters/javi.png", name: "Javi" },
    { src: "img/gallery/characters/jyoti.png", name: "Jyoti" },
    { src: "img/gallery/characters/kento.png", name: "Kento" },
    { src: "img/gallery/characters/kiowa.png", name: "Kiowa" },
    { src: "img/gallery/characters/leah.png", name: "Leah" },
    { src: "img/gallery/characters/legendarius.png", name: "Legendarius" },
    { src: "img/gallery/characters/liquaxis.png", name: "Liquaxis" },
    { src: "img/gallery/characters/louloudi.png", name: "Louloudi" },
    { src: "img/gallery/characters/masked.png", name: "Masked!Memphis" },
    { src: "img/gallery/characters/mauzie.png", name: "Mauzie" },
    { src: "img/gallery/characters/memphis.png", name: "Memphis" },
    { src: "img/gallery/characters/misty.png", name: "Misty" },
    { src: "img/gallery/characters/mono.png", name: "Mono" },
    { src: "img/gallery/characters/moxie.png", name: "Moxie" },
    { src: "img/gallery/characters/mosaic.png", name: "Mozaika" },
    { src: "img/gallery/characters/ms.clockworks.png", name: "Ms. Clockworks" },
    { src: "img/gallery/characters/mumtaz.png", name: "Mumtaz" },
    { src: "img/gallery/characters/nylon.png", name: "Nylon" },
    { src: "img/gallery/characters/nyxauris.png", name: "Nyxauris" },
    { src: "img/gallery/characters/oliver.png", name: "Oliver" },
    { src: "img/gallery/characters/omega.png", name: "Omega" },
    { src: "img/gallery/characters/pandora.png", name: "Pandora" },
    { src: "img/gallery/characters/polychroma.png", name: "Polychroma" },
    { src: "img/gallery/characters/prototot.png", name: "Prototot" },
    { src: "img/gallery/characters/quasibot.png", name: "Quasibot" },
    { src: "img/gallery/characters/quodara.png", name: "Quodara" },
    { src: "img/gallery/characters/rachel.png", name: "Rachel" },
    { src: "img/gallery/characters/rainbowpicasso.png", name: "Rainbow Picasso" },
    { src: "img/gallery/characters/ramachandra.png", name: "Ramachandra" },
    { src: "img/gallery/characters/red.png", name: "Red" },
    { src: "img/gallery/characters/ringo.png", name: "Ringo" },
    { src: "img/gallery/characters/rob.png", name: "Rob" },
    { src: "img/gallery/characters/roku.png", name: "Roku" },
    { src: "img/gallery/characters/rui.png", name: "Rui" },
    { src: "img/gallery/characters/sapphire.png", name: "Sapphire" },
    { src: "img/gallery/characters/simon.png", name: "Simon" },
    { src: "img/gallery/characters/skybot.png", name: "Skybot" },
    { src: "img/gallery/characters/slabby.png", name: "Slabby" },
    { src: "img/gallery/characters/spectrum.png", name: "Spectrum" },
    { src: "img/gallery/characters/stavros.png", name: "Stavros" },
    { src: "img/gallery/characters/subble.png", name: "Subble" },
    { src: "img/gallery/characters/tahir.png", name: "Tahir" },
    { src: "img/gallery/characters/tetranoid.png", name: "Tetranoid" },
    { src: "img/gallery/characters/time.png", name: "Time" },
    { src: "img/gallery/characters/tohomari.png", name: "Tohomari" },
    { src: "img/gallery/characters/tots.png", name: "Tots" },
    { src: "img/gallery/characters/ucunoid.png", name: "Ucunoid" },
    { src: "img/gallery/characters/usitron.png", name: "Usitron" },
    { src: "img/gallery/characters/victor.png", name: "Victor" },
    { src: "img/gallery/characters/vivian.png", name: "Vivian" },
    { src: "img/gallery/characters/xander.png", name: "Xander" },
    { src: "img/gallery/characters/xzavis.png", name: "Xzavis" },
    { src: "img/gallery/characters/zendy.png", name: "Zendy" }
];

const galleryContainer = document.getElementById("gallery-container");

galleryData.forEach((item, index) => {
    if (index % 4 === 0) {
        const galleryDiv = document.createElement("div");
        galleryDiv.className = "gallery";
        galleryContainer.appendChild(galleryDiv);
    }

    const galleryItem = document.createElement("div");
    galleryItem.className = "gallery-item";
    galleryItem.innerHTML = `<img src="${item.src}"> <p>${item.name}</p>`;
    galleryContainer.lastChild.appendChild(galleryItem);
});