const galleryData = [
    { src: "accord.png", name: "Accord" },
    { src: "akashi.png", name: "Akashi" },
    { src: "alpha.png", name: "Alpha" },
    { src: "amelia.png", name: "Amelia" },
    { src: "anomaly-x23g.png", name: "Anomaly-X23G" },
    { src: "aquarion.png", name: "Aquarion" },
    { src: "ari.png", name: "Ari" },
    { src: "aris.png", name: "Aris" },
    { src: "armen.png", name: "Armen" },
    { src: "asadullah.png", name: "Asadullah" },
    { src: "astroboy.png", name: "AstroBoy" },
    { src: "axol.png", name: "Axol" },
    { src: "ayun.png", name: "Ayun" },
    { src: "bandit.png", name: "Bandit Guy" },
    { src: "basya.png", name: "Basya" },
    { src: "bellboy.png", name: "Belldam" },
    { src: "benji.png", name: "Benji" },
    { src: "blair.png", name: "Blair" },
    { src: "bor.png", name: "boR" },
    { src: "bugger.png", name: "Bugger" },
    { src: "charis.png", name: "Charis" },
    { src: "chiffon.png", name: "Chiffon" },
    { src: "chiko.png", name: "Chiko" },
    { src: "circleguy.png", name: "Circle Guy" },
    { src: "clementina.png", name: "Clementina" },
    { src: "copykat.png", name: "CopyKat" },
    { src: "corruptus.png", name: "Corruptus" },
    { src: "creator.png", name: "Creator!Memphis" },
    { src: "crescendo.png", name: "Crescendo" },
    { src: "cubic.png", name: "Cubic" },
    { src: "dagon.png", name: "Dagon" },
    { src: "dango.png", name: "Dango" },
    { src: "dayaram.png", name: "Dayaram" },
    { src: "delta.png", name: "Delta" },
    { src: "demetrius.png", name: "Demetrius" },
    { src: "dendi.png", name: "Dendi" },
    { src: "deutera.png", name: "Deutera" },
    { src: "court.png", name: "Diamond!Memphis" },
    { src: "dillon.png", name: "Dillon" },
    { src: "doc.png", name: "Doc" },
    { src: "dune.png", name: "Dunic" },
    { src: "echo.png", name: "Echo" },
    { src: "edgar.png", name: "Edgar" },
    { src: "elle.png", name: "Elle" },
    { src: "emptier.png", name: "Emptier" },
    { src: "envy.png", name: "Envy" },
    { src: "espresso.png", name: "Espresso" },
    { src: "explorer.png", name: "Explorer" },
    { src: "flambu.png", name: "Flambu" },
    { src: "global.png", name: "Global" },
    { src: "goatis.png", name: "Goatis" },
    { src: "goldie.png", name: "Goldie" },
    { src: "grey.png", name: "Grey" },
    { src: "hanna.png", name: "Hanna" },
    { src: "healer.png", name: "Healer" },
    { src: "heliosol.png", name: "Heliosol" },
    { src: "hikari.png", name: "Hikari" },
    { src: "hilarion.png", name: "Hilarion" },
    { src: "homo.png", name: "Homo!Memphis" },
    { src: "hoodedspy.png", name: "Hooded Spy" },
    { src: "hoppa.png", name: "Hoppa" },
    { src: "ikram.png", name: "Ikram" },
    { src: "inflictor.png", name: "Inflictor" },
    { src: "iriseis.png", name: "Iriseis" },
    { src: "isamu.png", name: "Isamu" },
    { src: "isedroid.png", name: "Isedroid" },
    { src: "ixaptron.png", name: "Ixaptron" },
    { src: "javi.png", name: "Javi" },
    { src: "jyoti.png", name: "Jyoti" },
    { src: "kento.png", name: "Kento" },
    { src: "kiowa.png", name: "Kiowa" },
    { src: "leah.png", name: "Leah" },
    { src: "legendarius.png", name: "Legendarius" },
    { src: "liquaxis.png", name: "Liquaxis" },
    { src: "louloudi.png", name: "Louloudi" },
    { src: "masked.png", name: "Masked!Memphis" },
    { src: "mauzie.png", name: "Mauzie" },
    { src: "memphis.png", name: "Memphis" },
    { src: "misty.png", name: "Misty" },
    { src: "mono.png", name: "Mono" },
    { src: "moxie.png", name: "Moxie" },
    { src: "mosaic.png", name: "Mozaika" },
    { src: "ms.clockworks.png", name: "Ms. Clockworks" },
    { src: "mumtaz.png", name: "Mumtaz" },
    { src: "nylon.png", name: "Nylon" },
    { src: "nyxauris.png", name: "Nyxauris" },
    { src: "oliver.png", name: "Oliver" },
    { src: "omega.png", name: "Omega" },
    { src: "pandora.png", name: "Pandora" },
    { src: "polychroma.png", name: "Polychroma" },
    { src: "prototot.png", name: "Prototot" },
    { src: "quasibot.png", name: "Quasibot" },
    { src: "quodara.png", name: "Quodara" },
    { src: "rachel.png", name: "Rachel" },
    { src: "rainbowpicasso.png", name: "Rainbow Picasso" },
    { src: "ramachandra.png", name: "Ramachandra" },
    { src: "red.png", name: "Red" },
    { src: "ringo.png", name: "Ringo" },
    { src: "rob.png", name: "Rob" },
    { src: "roku.png", name: "Roku" },
    { src: "rui.png", name: "Rui" },
    { src: "sapphire.png", name: "Sapphire" },
    { src: "simon.png", name: "Simon" },
    { src: "skybot.png", name: "Skybot" },
    { src: "slabby.png", name: "Slabby" },
    { src: "spectrum.png", name: "Spectrum" },
    { src: "stavros.png", name: "Stavros" },
    { src: "subble.png", name: "Subble" },
    { src: "tahir.png", name: "Tahir" },
    { src: "tetranoid.png", name: "Tetranoid" },
    { src: "time.png", name: "Time" },
    { src: "tohomari.png", name: "Tohomari" },
    { src: "tots.png", name: "Tots" },
    { src: "ucunoid.png", name: "Ucunoid" },
    { src: "usitron.png", name: "Usitron" },
    { src: "victor.png", name: "Victor" },
    { src: "vivian.png", name: "Vivian" },
    { src: "xander.png", name: "Xander" },
    { src: "xzavis.png", name: "Xzavis" },
    { src: "zendy.png", name: "Zendy" }
];

const galleryContainer = document.getElementById("gallery-container");

galleryData.forEach((item, index) => {
    if (index % 4 === 0) {
        const galleryDiv = document.createElement("div");
        galleryDiv.className = "gallery";
        galleryContainer.appendChild(galleryDiv);
    }

    const galleryItem = document.createElement("div");
    galleryItem.className = "gallery-item";
    galleryItem.innerHTML = `<img src="img/gallery/characters/${item.src}"> <p>${item.name}</p>`;
    galleryContainer.lastChild.appendChild(galleryItem);
});